### ISSUE TITLE
Hypercon 1.03.1 with LibreELEC 7.0.2 doesn't install correctly over SSH

### ISSUE THREAD

**Issue by rudelm** [hyperion-project/hypercon#18]
Hi,

I'Ve tried to follow the instructions from https://hyperion-project.org/wiki/Installation-on-all-systems and I encountered an error, when I tried to install/update Hyperion:

<img width="816" alt="sshhyperioninstallerror" src="https://cloud.githubusercontent.com/assets/1426140/17570333/3c8dcf00-5f4c-11e6-9360-abc74243b6b0.png">

wget on LibreELEC doesn't support the -nv parameter. The -N is also not recognized, as the same error message happens, when I copy the command to a real SSH session in my terminal.

If you leave those parameters out, it will complain about sudo which isn't present in openelec. So for openelec the only working version of the command was

``cd /tmp && wget https://raw.github.com/hyperion-project/hyperion/master/bin/install_hyperion.sh && chmod +x install_hyperion.sh && sh ./install_hyperion.sh HyperConInstall ; rm install_hyperion.sh``

So my suggestion would be to change the installation page or to fix the OS detection in Hyperion accordingly.

**Comment by brindosch** [comment]
Greetings, there is a slight point you overseen, as there is a system selection at the top, the command will be different (curl and without sudo).
This will be improved in future to prevent almost every issue that could happen

**Comment by rudelm** [comment]
Oh my bad, didn't see that setting. I'll close the ticket then! Thanks for the fast response!
