### ISSUE TITLE
Compile instructions missing

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hypercon#19]
How do I compile this software?

I only found this page, which describes how to start the .jar file:
https://hyperion-project.org/wiki/HyperCon-Information

I find it quite interresting that there are instructions for redhat. RHEL servers with ambilight. Why not? Reminds me of using 2x Nvidia Quadro 4000 with a Server ;)

I'd expect compile information in the github and not the forum btw.

**Comment by WoLpH** [comment]
The tool will be replaced soon so it doesn't have that much priority anymore. 

For what it's worth though, building is as easy as:
```
gradle main
```

**Comment by NicoHood** [comment]
Thanks. But then I get `Error: Could not find or load main class org.hyperion.hypercon.Main` when launching the app with `java -jar`.

With what will it get replaced? I was about to make a PKGBUILD for it, but if its discontinued I won't put much energy in it.

**Comment by Paulchen-Panther** [comment]
http://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean

**Comment by WoLpH** [comment]
It will be replaced with hyperion.ng once it's done: https://github.com/hyperion-project/hyperion.ng

The Hypercon build script currently isn't complete unfortunately. It assumes you run it in a development setting where you have your IDE compiling the sources for you. The ant configuration could be amended to include that part but I think all efforts are currently pointed towards hyperion.ng :)

**Comment by NicoHood** [comment]
But does hyperion-ng have its own configuration tool? I expected hypercon will live on. Well then don't bother spending much time on this. I will use the jar file and we all wait for the next version of hyperion.

**Comment by tpmodding** [comment]
yes thanks.

**Comment by BTopbas** [comment]
I am so sorry for re-opening this topic. I need to change somethings in this configurator for my university project. But i can't build jar file. How to compile? I am using mac os x and i install gradle but i think i do something wrong. I want single jar file with my source edits. What can i do for compile? How? I want little help for start.

Thanks all community members for extremely hard work and this such a beauty hyperion system.
