### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by BTopbas** [hyperion-project/hypercon#29]
I am so sorry for re-opening this topic. I need to change somethings in this configurator for my university project. But i can't build jar file. How to compile? I am using mac os x and i install gradle but i think i do something wrong. I want single jar file with my source edits. What can i do for compile? How? I want little help for start.

Thanks all community members for extremely hard work and this such a beauty hyperion system.

**Comment by tpmodding** [comment]
should be fixed with #32
